### ISSUE TITLE
libc.so.6: version `GLIBC_2.34' not found 

### ISSUE THREAD

**Issue by razaqq** [blacksky3/mesa-git#1]
After installing `clang-git llvm-git llvm-libs-git` im getting

```console
$ clang
clang: /usr/bin/../lib/libc.so.6: version `GLIBC_2.34' not found (required by clang)
clang: /usr/bin/../lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/../lib/libclang-cpp.so.15git)
clang: /usr/bin/../lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/../lib/libLLVM-15git.so)
```

Same issue and discussion here https://bugs.archlinux.org/task/73730
The latest version of `glibc` in core is `2.33-5` (< `2.34`). https://archlinux.org/packages/core/x86_64/glibc/
Would it be possible to build these libs against `glibc` of core?

**Comment by blacksky3** [comment]
What is your current glibc version ?

**Comment by razaqq** [comment]
`core/glibc` actually got bumped to `2.35-2` today at `2022-02-14 20:31 UTC`, which fixed it

closing
